# --- !Ups

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teas (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  name VARCHAR(255) NOT NULL,
  tea_type VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  purchase_date DATE NOT NULL,
  price DECIMAL(10,2),
  weight DECIMAL(10,2),
  notes TEXT,
  created_at DATE NOT NULL DEFAULT CURRENT_DATE,
  updated_at DATE NOT NULL DEFAULT CURRENT_DATE
);

# --- !Downs

DROP TABLE IF EXISTS teas;
DROP TABLE IF EXISTS users; 