# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Verify project structure
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Project root contents ==="
        ls -la
        echo "=== package-lock.json status ==="
        if [ -f "package-lock.json" ]; then
          echo "✅ package-lock.json exists"
          ls -la package-lock.json
          echo "File size: $(wc -c < package-lock.json) bytes"
        else
          echo "❌ package-lock.json not found!"
        fi
        echo "=== package.json status ==="
        if [ -f "package.json" ]; then
          echo "✅ package.json exists"
          ls -la package.json
        else
          echo "❌ package.json not found!"
        fi
      
    - name: Clear all caches first
      run: |
        rm -rf node_modules
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'sbt'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        npm-version: '10.8.2'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Verify Node.js and npm installation
      run: |
        echo "Node.js version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "NPM location: $(which npm)"
        echo "NPM config: $(npm config list)"
        
        # Ensure npm is working
        npm --version
        npm config get registry
        
        # Verify npm is properly installed
        if ! command -v npm &> /dev/null; then
          echo "❌ npm command not found"
          exit 1
        fi
        
        # Check npm version is not undefined
        npm_version=$(npm --version)
        if [ "$npm_version" = "undefined" ] || [ -z "$npm_version" ]; then
          echo "❌ npm version is undefined or empty"
          echo "Attempting to reinstall npm..."
          npm install -g npm@10.8.2
          echo "NPM version after reinstall: $(npm --version)"
        else
          echo "✅ npm version is valid: $npm_version"
        fi
        
        # Final verification - test npm functionality
        echo "Testing npm functionality..."
        npm config get registry > /dev/null
        if [ $? -eq 0 ]; then
          echo "✅ npm is working correctly"
        else
          echo "❌ npm is not working correctly"
          echo "Attempting final npm reinstall..."
          npm install -g npm@10.8.2
          npm config get registry > /dev/null
          if [ $? -eq 0 ]; then
            echo "✅ npm is now working correctly"
          else
            echo "❌ npm is still not working - failing build"
            exit 1
          fi
        fi
        
    - name: Install npm dependencies
      run: |
        # Ensure we're in the project root
        pwd
        echo "=== Checking package-lock.json ==="
        if [ -f "package-lock.json" ]; then
          echo "package-lock.json exists, using npm ci"
          ls -la package-lock.json
          npm ci
        else
          echo "package-lock.json not found, generating it with npm install"
          npm install
        fi
        echo "Dependencies installed successfully"
        
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
        
    - name: Cache sbt dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          project/target
          target
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}-cache-v2
        restore-keys: |
          ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-
          ${{ runner.os }}-sbt-
          
    - name: Clean and update dependencies
      run: |
        # Clean and update dependencies
        sbt clean update
        
        # Verify dependencies - show actual resolved versions
        echo "=== Project dependencies ==="
        sbt "show libraryDependencies" | grep -E "(play-|scala-xml)" || echo "No Play Framework dependencies found"
        
    - name: Compile project
      run: sbt compile
        
    - name: Run tests
      run: sbt test
      
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
